version: "3.8"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: service_desk
    ports:
      - 3306:3306
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - service_desk_app
  server:
    build: ./server
    container_name: server_container
    depends_on:
      - mysql-db
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - ./server:/app
    environment:
      <<: *common-variables
    links:
      - mysql-db
    networks:
      - service_desk_app
  client:
    build: ./client
    container_name: client_container
    environment:
      NODE_PATH: src
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - ./client/src:/app/src
    links:
      - server
  
volumes:
  db_data:

networks:
  service_desk_app:
    driver: bridge